name: Build Pack
on:
  workflow_dispatch:
  #push:
    #branches:
      #- master 
jobs:
  pack: 
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest] 
    steps:
    - uses: actions/checkout@v2 
    - name: Install and Pack 
      run: |
        npm install
        npm install --save-dev @electron-forge/cli
        npx electron-forge import
        npm run make
    - name: Upload file
      uses: actions/upload-artifact@v2
      with:
        name: out/80z2.fun_electron-win32-x64
        path: WindowsOut
        name: out/80z2.fun_electron-darwin-x64
        path: macOS Out